exp_name: modelnet

model: RIENET
dataset: modelnet40
model_path: ''
dim: 8 # 16 for unseen experiment / 8 for the same experiment
# -------------------------modelenet40-------------------
rot_factor: 4 
gaussian_noise: False # add noise
unseen: False # True for unseen / False for the same

# -------------------------icl_nuim----------------------
max_angle: 45
max_trans: 0.5
data_file_test: ./data/test/icl_nuim.h5
data_file: ./data/train/icl_nuim.h5

# -------------------------7scenes-----------------------
mode: train
mag: 1
workers: 4
dataset-path: ./data/7scene
categoryfile: ./data/categories/7scene_train.txt

# --------------------------kitti-------------------------
voxel_size: 0.3
root: ./data/kitti_dataset/sequences/
data_list: ./data/kitti_list
augment: 1.0


# ----------------model hyper parameters------------------
nn_margin: 0.7
loss_margin: 0.01
list_k1: [5,5,5]
list_k2: [5,5,5]
emb_dims: 256
n_iters: 3
n_points: 1024
n_subsampled_points: 768
batch_size: 16
test_batch_size: 16
epochs: 50
use_sgd: False
n_keypoints: 256
lr: 0.001
momentum: 0.9
no_cuda: False
seed: 1234
start_epoch: 0
lr_step: [25, 50]

# ------------------network training-----------------------
resume: False

# ------------------network testing------------------------
eval: True # True for testing / False for training
